# Generated by Django 2.1.15 on 2023-02-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('link', models.CharField(default='', max_length=2083, unique=True)),
                ('language', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('section', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=20000, unique=True)),
                ('sentiment', models.CharField(max_length=20)),
            ],
        ),
    ]
